CREATE TABLE dbo.Klient (
	IdKlienta INT IDENTITY(1, 1) PRIMARY KEY
	,Imie VARCHAR(30) NOT NULL
	,Nazwisko VARCHAR(30) NOT NULL
	,PESEL CHAR(11) NOT NULL
	,NIP CHAR(13) NOT NULL
	,Ulica VARCHAR(30) NOT NULL
	,NrDomu VARCHAR(10) NOT NULL
	,NrLokalu VARCHAR(10) NULL
	,KodPocztowy CHAR(6) NOT NULL
	,Poczta VARCHAR(30) NOT NULL
	,Miejscowosc VARCHAR(30) NOT NULL
	,Email VARCHAR(50) NULL
	,Telefon VARCHAR(30) NULL
	,DataRejestracji DATETIME NOT NULL
	) GO